apiVersion: v1
kind: Service
metadata:
  name: yolo-app
spec:
  type: NodePort
  ports:
  - port: 5002
    targetPort: 5002
    nodePort: 30003  # Choose a port between 30000 and 32767
  selector:
    app: yolo-app
